#ifndef NBLIB_ATMEGA328PB_HPP
#define NBLIB_ATMEGA328PB_HPP

// #include "atmega328p.hpp"

#define NBLIB_CHIP_DEFINED

//------------------------------------------------
// Memory

#define CHIP_RAM_SIZE                                               (1024 * 2)

//------------------------------------------------
// Registers

#define CHIP_REG_PINB_ADDR                                          0x23
#define CHIP_REG_PINB_TYPE                                          uint8_t
#define CHIP_REG_DDRB_ADDR                                          0x24
#define CHIP_REG_DDRB_TYPE                                          uint8_t
#define CHIP_REG_PORTB_ADDR                                         0x25
#define CHIP_REG_PORTB_TYPE                                         uint8_t
#define CHIP_REG_PINC_ADDR                                          0x26
#define CHIP_REG_PINC_TYPE                                          uint8_t
#define CHIP_REG_DDRC_ADDR                                          0x27
#define CHIP_REG_DDRC_TYPE                                          uint8_t
#define CHIP_REG_PORTC_ADDR                                         0x28
#define CHIP_REG_PORTC_TYPE                                         uint8_t
#define CHIP_REG_PIND_ADDR                                          0x29
#define CHIP_REG_PIND_TYPE                                          uint8_t
#define CHIP_REG_DDRD_ADDR                                          0x2A
#define CHIP_REG_DDRD_TYPE                                          uint8_t
#define CHIP_REG_PORTD_ADDR                                         0x2B
#define CHIP_REG_PORTD_TYPE                                         uint8_t
#define CHIP_REG_PINE_ADDR                                          0x2C
#define CHIP_REG_PINE_TYPE                                          uint8_t
#define CHIP_REG_DDRE_ADDR                                          0x2D
#define CHIP_REG_DDRE_TYPE                                          uint8_t
#define CHIP_REG_PORTE_ADDR                                         0x2E
#define CHIP_REG_PORTE_TYPE                                         uint8_t
#define CHIP_REG_TIFR0_ADDR                                         0x35
#define CHIP_REG_TIFR0_TYPE                                         uint8_t
#define CHIP_REG_TIFR1_ADDR                                         0x36
#define CHIP_REG_TIFR1_TYPE                                         uint8_t
#define CHIP_REG_TIFR2_ADDR                                         0x37
#define CHIP_REG_TIFR2_TYPE                                         uint8_t
#define CHIP_REG_TIFR3_ADDR                                         0x38
#define CHIP_REG_TIFR3_TYPE                                         uint8_t
#define CHIP_REG_TIFR4_ADDR                                         0x39
#define CHIP_REG_TIFR4_TYPE                                         uint8_t
#define CHIP_REG_PCIFR_ADDR                                         0x3B
#define CHIP_REG_PCIFR_TYPE                                         uint8_t
#define CHIP_REG_EIFR_ADDR                                          0x3C
#define CHIP_REG_EIFR_TYPE                                          uint8_t
#define CHIP_REG_EIMSK_ADDR                                         0x3D
#define CHIP_REG_EIMSK_TYPE                                         uint8_t
#define CHIP_REG_GPIOR0_ADDR                                        0x3E
#define CHIP_REG_GPIOR0_TYPE                                        uint8_t
#define CHIP_REG_EECR_ADDR                                          0x3F
#define CHIP_REG_EECR_TYPE                                          uint8_t
#define CHIP_REG_EEDR_ADDR                                          0x40
#define CHIP_REG_EEDR_TYPE                                          uint8_t
#define CHIP_REG_EEAR_ADDR                                          0x41
#define CHIP_REG_EEAR_TYPE                                          uint16_t
#define CHIP_REG_GTCCR_ADDR                                         0x43
#define CHIP_REG_GTCCR_TYPE                                         uint8_t
#define CHIP_REG_TCCR0A_ADDR                                        0x44
#define CHIP_REG_TCCR0A_TYPE                                        uint8_t
#define CHIP_REG_TCCR0B_ADDR                                        0x45
#define CHIP_REG_TCCR0B_TYPE                                        uint8_t
#define CHIP_REG_TCNT0_ADDR                                         0x46
#define CHIP_REG_TCNT0_TYPE                                         uint8_t
#define CHIP_REG_OCR0A_ADDR                                         0x47
#define CHIP_REG_OCR0A_TYPE                                         uint8_t
#define CHIP_REG_OCR0B_ADDR                                         0x48
#define CHIP_REG_OCR0B_TYPE                                         uint8_t
#define CHIP_REG_GPIOR1_ADDR                                        0x4A
#define CHIP_REG_GPIOR1_TYPE                                        uint8_t
#define CHIP_REG_GPIOR2_ADDR                                        0x4B
#define CHIP_REG_GPIOR2_TYPE                                        uint8_t
#define CHIP_REG_SPCR0_ADDR                                         0x4C
#define CHIP_REG_SPCR0_TYPE                                         uint8_t
#define CHIP_REG_SPSR0_ADDR                                         0x4D
#define CHIP_REG_SPSR0_TYPE                                         uint8_t
#define CHIP_REG_SPDR0_ADDR                                         0x4E
#define CHIP_REG_SPDR0_TYPE                                         uint8_t
#define CHIP_REG_ACSR_ADDR                                          0x50
#define CHIP_REG_ACSR_TYPE                                          uint8_t
#define CHIP_REG_DWDR_ADDR                                          0x51
#define CHIP_REG_DWDR_TYPE                                          uint8_t
#define CHIP_REG_SMCR_ADDR                                          0x53
#define CHIP_REG_SMCR_TYPE                                          uint8_t
#define CHIP_REG_MCUSR_ADDR                                         0x54
#define CHIP_REG_MCUSR_TYPE                                         uint8_t
#define CHIP_REG_MCUCR_ADDR                                         0x55
#define CHIP_REG_MCUCR_TYPE                                         uint8_t
#define CHIP_REG_SPMCSR_ADDR                                        0x57
#define CHIP_REG_SPMCSR_TYPE                                        uint8_t
#define CHIP_REG_SP_ADDR                                            0x5D
#define CHIP_REG_SP_TYPE                                            uint16_t
#define CHIP_REG_SREG_ADDR                                          0x5F
#define CHIP_REG_SREG_TYPE                                          uint8_t
#define CHIP_REG_WDTCSR_ADDR                                        0x60
#define CHIP_REG_WDTCSR_TYPE                                        uint8_t
#define CHIP_REG_CLKPR_ADDR                                         0x61
#define CHIP_REG_CLKPR_TYPE                                         uint8_t
#define CHIP_REG_XFDCSR_ADDR                                        0x62
#define CHIP_REG_XFDCSR_TYPE                                        uint8_t
#define CHIP_REG_PRR0_ADDR                                          0x64
#define CHIP_REG_PRR0_TYPE                                          uint8_t
#define CHIP_REG_OSCCAL_ADDR                                        0x66
#define CHIP_REG_OSCCAL_TYPE                                        uint8_t
#define CHIP_REG_PCICR_ADDR                                         0x68
#define CHIP_REG_PCICR_TYPE                                         uint8_t
#define CHIP_REG_EICRA_ADDR                                         0x69
#define CHIP_REG_EICRA_TYPE                                         uint8_t
#define CHIP_REG_PCMSK0_ADDR                                        0x6B
#define CHIP_REG_PCMSK0_TYPE                                        uint8_t
#define CHIP_REG_PCMSK1_ADDR                                        0x6C
#define CHIP_REG_PCMSK1_TYPE                                        uint8_t
#define CHIP_REG_PCMSK2_ADDR                                        0x6D
#define CHIP_REG_PCMSK2_TYPE                                        uint8_t
#define CHIP_REG_TIMSK0_ADDR                                        0x6E
#define CHIP_REG_TIMSK0_TYPE                                        uint8_t
#define CHIP_REG_TIMSK1_ADDR                                        0x6F
#define CHIP_REG_TIMSK1_TYPE                                        uint8_t
#define CHIP_REG_TIMSK2_ADDR                                        0x70
#define CHIP_REG_TIMSK2_TYPE                                        uint8_t
#define CHIP_REG_TIMSK3_ADDR                                        0x71
#define CHIP_REG_TIMSK3_TYPE                                        uint8_t
#define CHIP_REG_TIMSK4_ADDR                                        0x72
#define CHIP_REG_TIMSK4_TYPE                                        uint8_t
#define CHIP_REG_ADC_ADDR                                           0x78
#define CHIP_REG_ADC_TYPE                                           uint16_t
#define CHIP_REG_ADCSRA_ADDR                                        0x7A
#define CHIP_REG_ADCSRA_TYPE                                        uint8_t
#define CHIP_REG_ADCSRB_ADDR                                        0x7B
#define CHIP_REG_ADCSRB_TYPE                                        uint8_t
#define CHIP_REG_ADMUX_ADDR                                         0x7C
#define CHIP_REG_ADMUX_TYPE                                         uint8_t
#define CHIP_REG_DIDR0_ADDR                                         0x7E
#define CHIP_REG_DIDR0_TYPE                                         uint8_t
#define CHIP_REG_DIDR1_ADDR                                         0x7F
#define CHIP_REG_DIDR1_TYPE                                         uint8_t
#define CHIP_REG_TCCR1A_ADDR                                        0x80
#define CHIP_REG_TCCR1A_TYPE                                        uint8_t
#define CHIP_REG_TCCR1B_ADDR                                        0x81
#define CHIP_REG_TCCR1B_TYPE                                        uint8_t
#define CHIP_REG_TCCR1C_ADDR                                        0x82
#define CHIP_REG_TCCR1C_TYPE                                        uint8_t
#define CHIP_REG_TCNT1_ADDR                                         0x84
#define CHIP_REG_TCNT1_TYPE                                         uint16_t
#define CHIP_REG_ICR1_ADDR                                          0x86
#define CHIP_REG_ICR1_TYPE                                          uint16_t
#define CHIP_REG_OCR1A_ADDR                                         0x88
#define CHIP_REG_OCR1A_TYPE                                         uint16_t
#define CHIP_REG_OCR1B_ADDR                                         0x8A
#define CHIP_REG_OCR1B_TYPE                                         uint16_t
#define CHIP_REG_TCCR3A_ADDR                                        0x90
#define CHIP_REG_TCCR3A_TYPE                                        uint8_t
#define CHIP_REG_TCCR3B_ADDR                                        0x91
#define CHIP_REG_TCCR3B_TYPE                                        uint8_t
#define CHIP_REG_TCCR3C_ADDR                                        0x92
#define CHIP_REG_TCCR3C_TYPE                                        uint8_t
#define CHIP_REG_TCNT3_ADDR                                         0x94
#define CHIP_REG_TCNT3_TYPE                                         uint16_t
#define CHIP_REG_ICR3_ADDR                                          0x96
#define CHIP_REG_ICR3_TYPE                                          uint16_t
#define CHIP_REG_OCR3A_ADDR                                         0x98
#define CHIP_REG_OCR3A_TYPE                                         uint16_t
#define CHIP_REG_OCR3B_ADDR                                         0x9A
#define CHIP_REG_OCR3B_TYPE                                         uint16_t
#define CHIP_REG_TCCR4A_ADDR                                        0xA0
#define CHIP_REG_TCCR4A_TYPE                                        uint8_t
#define CHIP_REG_TCCR4B_ADDR                                        0xA1
#define CHIP_REG_TCCR4B_TYPE                                        uint8_t
#define CHIP_REG_TCCR4C_ADDR                                        0xA2
#define CHIP_REG_TCCR4C_TYPE                                        uint8_t
#define CHIP_REG_TCNT4_ADDR                                         0xA4
#define CHIP_REG_TCNT4_TYPE                                         uint16_t
#define CHIP_REG_ICR4_ADDR                                          0xA6
#define CHIP_REG_ICR4_TYPE                                          uint16_t
#define CHIP_REG_DCR4B_ADDR                                         0xAA
#define CHIP_REG_DCR4B_TYPE                                         uint16_t
#define CHIP_REG_SPCR1_ADDR                                         0xAC
#define CHIP_REG_SPCR1_TYPE                                         uint16_t
#define CHIP_REG_SPSR1_ADDR                                         0xAD
#define CHIP_REG_SPSR1_TYPE                                         uint16_t
#define CHIP_REG_SPDR1_ADDR                                         0xAE
#define CHIP_REG_SPDR1_TYPE                                         uint16_t
#define CHIP_REG_TCCR2A_ADDR                                        0xB0
#define CHIP_REG_TCCR2A_TYPE                                        uint8_t
#define CHIP_REG_TCCR2B_ADDR                                        0xB1
#define CHIP_REG_TCCR2B_TYPE                                        uint8_t
#define CHIP_REG_TCNT2_ADDR                                         0xB2
#define CHIP_REG_TCNT2_TYPE                                         uint8_t
#define CHIP_REG_OCR2A_ADDR                                         0xB3
#define CHIP_REG_OCR2A_TYPE                                         uint8_t
#define CHIP_REG_OCR2B_ADDR                                         0xB4
#define CHIP_REG_OCR2B_TYPE                                         uint8_t
#define CHIP_REG_ASSR_ADDR                                          0xB6
#define CHIP_REG_ASSR_TYPE                                          uint8_t
#define CHIP_REG_TWBR0_ADDR                                         0xB8
#define CHIP_REG_TWBR0_TYPE                                         uint8_t
#define CHIP_REG_TWSR0_ADDR                                         0xB9
#define CHIP_REG_TWSR0_TYPE                                         uint8_t
#define CHIP_REG_TWAR0_ADDR                                         0xBA
#define CHIP_REG_TWAR0_TYPE                                         uint8_t
#define CHIP_REG_TWDR0_ADDR                                         0xBB
#define CHIP_REG_TWDR0_TYPE                                         uint8_t
#define CHIP_REG_TWCR0_ADDR                                         0xBC
#define CHIP_REG_TWCR0_TYPE                                         uint8_t
#define CHIP_REG_TWAMR0_ADDR                                        0xBD
#define CHIP_REG_TWAMR0_TYPE                                        uint8_t
#define CHIP_REG_UCSR0A_ADDR                                        0xC0
#define CHIP_REG_UCSR0A_TYPE                                        uint8_t
#define CHIP_REG_UCSR0B_ADDR                                        0xC1
#define CHIP_REG_UCSR0B_TYPE                                        uint8_t
#define CHIP_REG_UCSR0C_ADDR                                        0xC2
#define CHIP_REG_UCSR0C_TYPE                                        uint8_t
#define CHIP_REG_UBRR0_ADDR                                         0xC4
#define CHIP_REG_UBRR0_TYPE                                         uint16_t
#define CHIP_REG_UDR0_ADDR                                          0xC6
#define CHIP_REG_UDR0_TYPE                                          uint8_t
#define CHIP_REG_UCSR1A_ADDR                                        0xC8
#define CHIP_REG_UCSR1A_TYPE                                        uint8_t
#define CHIP_REG_UCSR1B_ADDR                                        0xC9
#define CHIP_REG_UCSR1B_TYPE                                        uint8_t
#define CHIP_REG_UCSR1C_ADDR                                        0xCA
#define CHIP_REG_UCSR1C_TYPE                                        uint8_t
#define CHIP_REG_UBRR1_ADDR                                         0xCC
#define CHIP_REG_UBRR1_TYPE                                         uint16_t
#define CHIP_REG_UDR1_ADDR                                          0xCE
#define CHIP_REG_UDR1_TYPE                                          uint8_t
#define CHIP_REG_TWBR1_ADDR                                         0xD8
#define CHIP_REG_TWBR1_TYPE                                         uint8_t
#define CHIP_REG_TWSR1_ADDR                                         0xD9
#define CHIP_REG_TWSR1_TYPE                                         uint8_t
#define CHIP_REG_TWAR1_ADDR                                         0xDA
#define CHIP_REG_TWAR1_TYPE                                         uint8_t
#define CHIP_REG_TWDR1_ADDR                                         0xDB
#define CHIP_REG_TWDR1_TYPE                                         uint8_t
#define CHIP_REG_TWCR1_ADDR                                         0xDC
#define CHIP_REG_TWCR1_TYPE                                         uint8_t
#define CHIP_REG_TWAMR1_ADDR                                        0xDD
#define CHIP_REG_TWAMR1_TYPE                                        uint8_t
#define CHIP_REG_OCR4A_ADDR                                         0x09A8
#define CHIP_REG_OCR4A_TYPE                                         uint16_t

//------------------------------------------------
// Vectors

#define CHIP_VECT_RESET                                             1
#define CHIP_VECT_INT0                                              2
#define CHIP_VECT_INT1                                              3
#define CHIP_VECT_PCINT0                                            4
#define CHIP_VECT_PCINT1                                            5
#define CHIP_VECT_PCINT2                                            6
#define CHIP_VECT_WDT                                               7
#define CHIP_VECT_TIMER2_COMPA                                      8
#define CHIP_VECT_TIMER2_COMPB                                      9
#define CHIP_VECT_TIMER2_OVF                                        10
#define CHIP_VECT_TIMER1_CAPT                                       11
#define CHIP_VECT_TIMER1_COMPA                                      12
#define CHIP_VECT_TIMER1_COMPB                                      13
#define CHIP_VECT_TIMER1_OVF                                        14
#define CHIP_VECT_TIMER0_COMPA                                      15
#define CHIP_VECT_TIMER0_COMPB                                      16
#define CHIP_VECT_TIMER0_OVF                                        17
#define CHIP_VECT_SPI0_STC                                          18
#define CHIP_VECT_USART0_RX                                         19
#define CHIP_VECT_USART0_UDRE                                       20
#define CHIP_VECT_USART0_TX                                         21
#define CHIP_VECT_ADC                                               22
#define CHIP_VECT_EE_READY                                          23
#define CHIP_VECT_ANALOG_COMP                                       24
#define CHIP_VECT_TWI                                               25
#define CHIP_VECT_SPM_READY                                         26
#define CHIP_VECT_USART0_START                                      27
#define CHIP_VECT_PCINT3                                            28
#define CHIP_VECT_USART1_RX                                         29
#define CHIP_VECT_USART1_UDRE                                       30
#define CHIP_VECT_USART1_TX                                         31
#define CHIP_VECT_USART1_START                                      32
#define CHIP_VECT_TIMER3_CAPT                                       33
#define CHIP_VECT_TIMER3_COMPA                                      34
#define CHIP_VECT_TIMER3_COMPB                                      35
#define CHIP_VECT_TIMER3_OVF                                        36
#define CHIP_VECT_CFD                                               37
#define CHIP_VECT_PTC_EOC                                           38
#define CHIP_VECT_PTC_WCOMP                                         39
#define CHIP_VECT_SPI1_STC                                          40
#define CHIP_VECT_TWI1                                              41
#define CHIP_VECT_TIMER4_CAPT                                       42
#define CHIP_VECT_TIMER4_COMPA                                      43
#define CHIP_VECT_TIMER4_COMPB                                      44
#define CHIP_VECT_TIMER4_OVF                                        45

//------------------------------------------------
// System

// Possibly need IDs for chips which have inhibit instead of enable.
#define CHIP_SYSTEM_GLOBAL_INTERRUPT_BIT_0_REG                      CHIP_REG_SREG
#define CHIP_SYSTEM_GLOBAL_INTERRUPT_BIT_0_BIT                      7

#endif
