#ifndef NBOS_HPP
#define NBOS_HPP

#include "algorithm.hpp"
#include "array.hpp"
#include "atomic.hpp"
#include "clock.hpp"
#include "i2c.hpp"
#include "initializer_list.hpp"
#include "iterator.hpp"
#include "macros.hpp"
#include "math.hpp"
#include "print.hpp"
#include "priorityqueue.hpp"
#include "queue.hpp"
#include "random.hpp"
#include "safe.hpp"
#include "serial.hpp"
#include "stack.hpp"
#include "string.hpp"
#include "task.hpp"
#include "taskmanager.hpp"
#include "tasks.hpp"

#include "hardware/adc.hpp"
#include "hardware/eeprom.hpp"
#include "hardware/exint.hpp"
#include "hardware/pcint.hpp"
#include "hardware/port.hpp"
#include "hardware/spi.hpp"
#include "hardware/timer.hpp"
#include "hardware/twi.hpp"
#include "hardware/usart.hpp"
#include "hardware/usi.hpp"
#include "hardware/watchdog.hpp"

#endif
